// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// AwsService is an autogenerated mock type for the AwsService type
type AwsService struct {
	mock.Mock
}

// S3ItemExists provides a mock function with given fields: productID, fileExt, imageType
func (_m *AwsService) S3ItemExists(productID string, fileExt string, imageType string) bool {
	ret := _m.Called(productID, fileExt, imageType)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(productID, fileExt, imageType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UploadItemToS3 provides a mock function with given fields: file, fileExt, productID, imageType
func (_m *AwsService) UploadItemToS3(file []byte, fileExt string, productID string, imageType string) error {
	ret := _m.Called(file, fileExt, productID, imageType)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string, string, string) error); ok {
		r0 = rf(file, fileExt, productID, imageType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
